name = "EasyHamiltonian"
uuid = "2159d8ee-d864-40aa-bd59-dded401e3f60"
authors = ["Qi Yang <qiyang@mail.ustc.edu.cn> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
